name: Hello World
on: push

jobs:
    hello-job:
        name: Hello job
        runs-on: ubuntu-latest

        steps:
            - name: Echo test
              run: echo "Hello, world!"
